name: ComuniApp CI Frontend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo fuente
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Verificar Estilo de Codigo (Lint)
      run: npm run lint

    # - name: Ejecutar Pruebas Unitarias
    #   run: npm run test -- --coverage
    